// <auto-generated />
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(SyscscContext))]
    [Migration("20200614222313_TablasUsoSueloYManejocultivo")]
    partial class TablasUsoSueloYManejocultivo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entity.Agroclimatica", b =>
                {
                    b.Property<int>("AgroclimaticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnalisisSuelo")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Este")
                        .HasColumnType("text");

                    b.Property<string>("FechaRealizacion")
                        .HasColumnType("text");

                    b.Property<string>("Latitud")
                        .HasColumnType("text");

                    b.Property<string>("MSNM")
                        .HasColumnType("text");

                    b.Property<string>("NorteLongitud")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PlanFertilizacion")
                        .HasColumnType("text");

                    b.Property<string>("PreparacionAbono")
                        .HasColumnType("text");

                    b.Property<int>("ProductorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<string>("TipoTextura")
                        .HasColumnType("text");

                    b.HasKey("AgroclimaticaId");

                    b.HasIndex("ProductorId")
                        .IsUnique();

                    b.ToTable("Agroclimaticas");
                });

            modelBuilder.Entity("Entity.Cultivo", b =>
                {
                    b.Property<int>("CultivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CultivoId");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("Entity.DatosFamilia", b =>
                {
                    b.Property<int>("Identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AfilicionSalud")
                        .HasColumnType("text");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("text");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<int>("ProductorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoPoblacion")
                        .HasColumnType("text");

                    b.HasKey("Identificacion");

                    b.HasIndex("ProductorId");

                    b.ToTable("DatosFamilias");
                });

            modelBuilder.Entity("Entity.InsumoExterno", b =>
                {
                    b.Property<int>("InsumoExternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cantidad")
                        .HasColumnType("text");

                    b.Property<string>("Composicion")
                        .HasColumnType("text");

                    b.Property<string>("Dosis")
                        .HasColumnType("text");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<string>("FechaAplicacion")
                        .HasColumnType("text");

                    b.Property<string>("LugarAplicacion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int>("ProductorId")
                        .HasColumnType("int");

                    b.Property<string>("RegistroICA")
                        .HasColumnType("text");

                    b.HasKey("InsumoExternoId");

                    b.HasIndex("ProductorId");

                    b.ToTable("InsumoExternos");
                });

            modelBuilder.Entity("Entity.InsumoInterno", b =>
                {
                    b.Property<int>("InsumoInternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cantidad")
                        .HasColumnType("text");

                    b.Property<string>("Dosis")
                        .HasColumnType("text");

                    b.Property<string>("FechaAplicacion")
                        .HasColumnType("text");

                    b.Property<string>("LugarAplicacion")
                        .HasColumnType("text");

                    b.Property<string>("MaterialesUsado")
                        .HasColumnType("text");

                    b.Property<string>("MetodoPreparacion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Procedimiento")
                        .HasColumnType("text");

                    b.Property<int>("ProductorId")
                        .HasColumnType("int");

                    b.Property<string>("TiempoPreparacion")
                        .HasColumnType("text");

                    b.HasKey("InsumoInternoId");

                    b.HasIndex("ProductorId");

                    b.ToTable("InsumoInternos");
                });

            modelBuilder.Entity("Entity.ManejoCultivo", b =>
                {
                    b.Property<int>("ManejoCultivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgroclimaticaId")
                        .HasColumnType("int");

                    b.Property<string>("DistanciaSiembra")
                        .HasColumnType("text");

                    b.Property<string>("FechaSiembra")
                        .HasColumnType("text");

                    b.Property<string>("Lote")
                        .HasColumnType("text");

                    b.Property<string>("NumeroArboles")
                        .HasColumnType("text");

                    b.Property<string>("SistemaRenovacion")
                        .HasColumnType("text");

                    b.Property<string>("Variedad")
                        .HasColumnType("text");

                    b.HasKey("ManejoCultivoId");

                    b.HasIndex("AgroclimaticaId");

                    b.ToTable("ManejoCultivos");
                });

            modelBuilder.Entity("Entity.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MunicipioId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("Entity.Productor", b =>
                {
                    b.Property<int>("ProductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividades")
                        .HasColumnType("text");

                    b.Property<string>("AfiliacionSalud")
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("CedulaCafetera")
                        .HasColumnType("text");

                    b.Property<string>("CodigoFinca")
                        .HasColumnType("text");

                    b.Property<string>("CodigoSICA")
                        .HasColumnType("text");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("NombrePredio")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("ProductorId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Productores");
                });

            modelBuilder.Entity("Entity.UsoSuelo", b =>
                {
                    b.Property<int>("UsoSueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgroclimaticaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Lote")
                        .HasColumnType("text");

                    b.Property<string>("Pendiente")
                        .HasColumnType("text");

                    b.Property<string>("PlanteadoProximoAno")
                        .HasColumnType("text");

                    b.Property<string>("PresentaErosion")
                        .HasColumnType("text");

                    b.Property<string>("Sombrio")
                        .HasColumnType("text");

                    b.Property<string>("Usos")
                        .HasColumnType("text");

                    b.HasKey("UsoSueloId");

                    b.HasIndex("AgroclimaticaId");

                    b.ToTable("UsoSuelos");
                });

            modelBuilder.Entity("Entity.Usuario", b =>
                {
                    b.Property<string>("NumeroCedula")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("text");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TipoUsuarioNombre")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioI")
                        .HasColumnType("text");

                    b.HasKey("NumeroCedula");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Entity.Agroclimatica", b =>
                {
                    b.HasOne("Entity.Productor", null)
                        .WithOne("Agroclimatica")
                        .HasForeignKey("Entity.Agroclimatica", "ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.DatosFamilia", b =>
                {
                    b.HasOne("Entity.Productor", null)
                        .WithMany("DatosFamilias")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.InsumoExterno", b =>
                {
                    b.HasOne("Entity.Productor", null)
                        .WithMany("InsumoExternos")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.InsumoInterno", b =>
                {
                    b.HasOne("Entity.Productor", null)
                        .WithMany("InsumoInternos")
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.ManejoCultivo", b =>
                {
                    b.HasOne("Entity.Agroclimatica", null)
                        .WithMany("ManejoCultivos")
                        .HasForeignKey("AgroclimaticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Productor", b =>
                {
                    b.HasOne("Entity.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.UsoSuelo", b =>
                {
                    b.HasOne("Entity.Agroclimatica", null)
                        .WithMany("UsoSuelos")
                        .HasForeignKey("AgroclimaticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
